export const allComponents = [
  {
    title: "input",
    image: "https://i.ibb.co/b1CyMNK/Name-1.png",
    url: "/components/input-text",
    groupName: "input",
  },
  {
    title: "textarea",
    image: "https://i.ibb.co/cb7cMxn/Name-20.png",
    url: "/components/input-textarea",
    groupName: "input",
  },
  {
    title: "switch",
    image: "https://i.ibb.co/X2QR7c3/Name-2.png",
    url: "/components/input-switch",
    groupName: "input",
  },
  {
    title: "radio",
    image: "https://i.ibb.co/kGh9ppd/Name-21.png",
    url: "/components/input-radio",
    groupName: "input",
  },
  {
    title: "file upload",
    image: "https://i.ibb.co/gmTJPyf/Name-23.png",
    url: "/components/input-file",
    groupName: "input",
  },
  {
    title: "primary button",
    image: "https://i.ibb.co/6R0WRr5/Name-4.png",
    url: "/components/normal-button",
    groupName: "button",
  },
  {
    title: "RGB border",
    image: "https://i.ibb.co/ZBQb1PC/Name-16.png",
    url: "/components/rgb-border",
    groupName: "button",
  },
  {
    title: "animated button",
    image: "https://i.ibb.co/6R0WRr5/Name-4.png",
    url: "/components/animated-button",
    groupName: "button",
  },
  {
    title: "chip",
    image: "https://i.ibb.co/wRnjstr/Name-5.png",
    url: "/components/chip",
    groupName: "navigation",
  },
  {
    title: "dropdown",
    image: "https://i.ibb.co/HYK8SPV/Name-24.png",
    url: "/components/dropdown",
    groupName: "navigation",
  },
  {
    title: "tab",
    image: "https://i.ibb.co/tzFdVZt/Name-14.png",
    url: "/components/tabs",
    groupName: "navigation",
  },
  {
    title: "modal",
    image: "https://i.ibb.co/yFRHYKV/Name-17.png",
    url: "/components/modal",
    groupName: "navigation",
  },
  {
    title: "pagination",
    image: "https://i.ibb.co/C9ytCym/Name-15.png",
    url: "/components/pagination",
    groupName: "navigation",
  },
  {
    title: "tooltip",
    image: "https://i.ibb.co/mcF2bX8/Name-7.png",
    url: "/components/tooltip",
    groupName: "data_display",
  },
  {
    title: "badge",
    image: "https://i.ibb.co/HgvLrtK/Name-6.png",
    url: "/components/badge",
    groupName: "data_display",
  },
  {
    title: "alert message",
    image: "https://i.ibb.co/2j1WcwK/Name-8.png",
    url: "/components/alert-message",
    groupName: "feedback",
  },
  {
    title: "skeleton",
    image: "https://i.ibb.co/xG5hNKD/Name-9.png",
    url: "/components/skeleton",
    groupName: "feedback",
  },
  {
    title: "loader",
    image: "https://i.ibb.co/WPBr497/Name-19.png",
    url: "/components/loader",
    groupName: "feedback",
  },
  {
    title: "according",
    image: "https://i.ibb.co/0Gpp2jv/Name-13.png",
    url: "/components/according",
    groupName: "surface",
  },
  {
    title: "card",
    image: "https://i.ibb.co/ChStSmV/Name-12.png",
    url: "/components/cards",
    groupName: "surface",
  },
  {
    title: "appbar",
    image: "https://i.ibb.co/ccS8kBn/Name-11.png",
    url: "/components/appbar",
    groupName: "surface",
  },
  {
    title: "image gallery",
    image: "https://i.ibb.co/KmFZSw0/Name-18.png",
    url: "/components/image-gallery",
    groupName: "surface",
  },
];
