export const resourcesData = [
    {
        id: 1,
        logo: 'https://i.ibb.co.com/2vDkJh2/https-dev-to-uploads-s3-amazonaws-com-uploads-organization-profile-image-356-ceb8dc0f-a77b-4f89-84da.png',
        name: 'Daily.Dev',
        description: 'Daily.dev is a platform for developers to stay updated with the latest tech news, tutorials, and resources. It curates top content from various sources, providing a personalized feed to enhance learning and skills.',
        websiteUrl: 'https://daily.dev/',
        isBookmarked: false,
        languages: [],
        isNPM: false,
    },
    {
        id: 2,
        logo: 'https://i.ibb.co.com/wwfH85Z/1817991c31c535d0.png',
        name: 'CSS Tricks',
        description: 'CSS-Tricks is a popular website offering articles, tutorials, and tips on CSS, web design, and front-end development. It provides valuable insights on layout techniques, animations, frameworks, and responsive design.',
        websiteUrl: 'https://css-tricks.com/',
        isBookmarked: false,
        languages: [
            'css'
        ],
        isNPM: false,
    },
    {
        id: 3,
        logo: 'https://i.ibb.co.com/J2mjjv2/304702060-474844821306824-3479081658794433305-n.png',
        name: 'Front-End Mentor',
        description: 'Frontend Mentor is a platform that provides real-world front-end challenges to help developers improve their coding skills. Users can work on responsive web projects, share solutions, and get feedback from the community.',
        websiteUrl: 'https://www.frontendmentor.io/',
        isBookmarked: false,
        languages: [
            'css',
            'react',
            'javascript'
        ],
        isNPM: false,
    },
    {
        id: 4,
        logo: 'https://i.ibb.co.com/FDCMtP0/GHQwf-YZWIAA55-WN.png',
        name: 'MDN web docs',
        description: 'MDN Web Docs is a comprehensive resource for web developers, providing documentation, tutorials, and references for web technologies like HTML, CSS, JavaScript, and APIs. It offers detailed guides and best practices for both beginners and experienced developers.',
        websiteUrl: 'https://developer.mozilla.org/',
        isBookmarked: false,
        languages: [
            'css',
            'javascript'
        ],
        isNPM: false,
    },
    {
        id: 5,
        logo: 'https://i.ibb.co.com/59rppJB/Flexbox-Froggy-Frog-green-color-assist-svg.png',
        name: 'flexbox froggy',
        description: 'Flexbox Froggy is an interactive game designed to teach CSS Flexbox concepts. Players guide a frog to its lily pad by writing CSS code, learning how Flexbox properties like justify-content and align-items work in a fun, hands-on way.',
        websiteUrl: 'https://flexboxfroggy.com/',
        isBookmarked: false,
        languages: [
            'css'
        ],
        isNPM: false,
    },
    {
        id: 6,
        logo: 'https://i.ibb.co.com/ccp9gnK/729x308.png',
        name: 'grid garden',
        description: 'Grid Garden is an interactive game that teaches CSS Grid layout. Players water a virtual garden by writing CSS Grid code, learning how grid properties like `grid-column` and `grid-row` work through engaging, hands-on challenges.',
        websiteUrl: 'https://cssgridgarden.com/',
        isBookmarked: false,
        languages: [
            'css'
        ],
        isNPM: false,
    },
    {
        id: 7,
        logo: 'https://i.ibb.co.com/6Ymzq6M/cover.jpg',
        name: 'Eloquent JavaScript',
        description: 'Eloquent JavaScript is a popular book by Marijn Haverbeke that provides an in-depth introduction to JavaScript and programming. It covers core concepts, advanced techniques, and practical exercises, making it an essential resource for both beginner and intermediate developers looking to master JavaScript.',
        websiteUrl: 'https://eloquentjavascript.net/',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: false,
    },
    {
        id: 8,
        logo: 'https://i.ibb.co.com/4Jpq6jP/site-preview-en-512x512.png',
        name: 'JavaScript info',
        description: 'JavaScript.info is a comprehensive tutorial website for learning modern JavaScript from the basics to advanced topics. It covers a wide range of subjects, including language fundamentals, browser interaction, asynchronous programming, and more, with clear explanations and interactive examples to help developers deepen their understanding.',
        websiteUrl: 'https://javascript.info/',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: false,
    },
    {
        id: 9,
        logo: 'https://i.ibb.co.com/D9QfGyf/978-1-4842-0076-6.jpg',
        name: 'the Pro Git Book',
        description: 'The Pro Git Book is a free online resource that offers a comprehensive guide to Git. It covers everything from basic commands to advanced features, making it essential for developers at any level.',
        websiteUrl: 'https://git-scm.com/book/en/v2',
        isBookmarked: false,
        languages: [
            'git & github'
        ],
        isNPM: false,
    },
    {
        id: 10,
        logo: 'https://i.ibb.co.com/w4cxGSV/logo.png',
        name: 'Material UI',
        description: 'Material UI is a popular React UI framework that offers customizable components based on Material Design, helping developers create responsive and visually appealing web applications efficiently.',
        websiteUrl: 'https://mui.com/',
        isBookmarked: false,
        languages: [
            'react',
            'ui library'
        ],
        isNPM: false,
    },
    {
        id: 11,
        logo: 'https://i.ibb.co.com/T0W5sL4/ant-design-icon-2048x2046-dl3neb73.png',
        name: 'Ant Design',
        description: 'Ant Design is a comprehensive design system and React UI framework developed by Alibaba. It provides a wide range of high-quality, reusable components and guidelines for building elegant and user-friendly web applications, emphasizing consistency and user experience.',
        websiteUrl: 'https://ant.design/',
        isBookmarked: false,
        languages: [
            'react',
            'ui library'
        ],
        isNPM: false,
    },
    {
        id: 12,
        logo: 'https://i.ibb.co.com/L1szYyp/54212428.png',
        name: 'chakra ui',
        description: 'Chakra UI is a modular React component library that helps developers create accessible and responsive UIs. It features customizable components and a theme system for consistent design and quick development.',
        websiteUrl: 'https://v2.chakra-ui.com/',
        isBookmarked: false,
        languages: [
            'react',
            'ui library'
        ],
        isNPM: false,
    },
    {
        id: 13,
        logo: 'https://i.ibb.co.com/GpLC5YL/vuetify-logo-CC59-D65-FD3-seeklogo-com.png',
        name: 'vueify',
        description: 'Vueify is a Vue.js plugin that allows you to use single-file components (SFCs) in your Vue applications. It simplifies the development process by enabling Vue components to be written in a single `.vue` file, combining HTML, CSS, and JavaScript, making it easier to manage and maintain your code.',
        websiteUrl: 'https://vuetifyjs.com/en/',
        isBookmarked: false,
        languages: [
            'vue'
        ],
        isNPM: false,
    },
    {
        id: 14,
        logo: 'https://i.ibb.co.com/dPsJ3G1/images-1.png',
        name: 'Element Plus',
        description: 'Element Plus is a Vue 3 UI framework that offers a wide range of customizable components for building elegant and responsive web applications, streamlining the development of professional interfaces.',
        websiteUrl: 'https://element-plus.org/en-US/',
        isBookmarked: false,
        languages: [
            'vue',
            'ui library'
        ],
        isNPM: false,
    },
    {
        id: 15,
        logo: 'https://i.ibb.co.com/hdRgF3D/13142323.png',
        name: 'redux',
        description: 'Redux is a predictable state management library for JavaScript applications, commonly used with React. It provides a central store for managing application state, enabling consistent state updates through actions and reducers, which simplifies debugging and enhances maintainability.',
        websiteUrl: 'https://redux.js.org/',
        isBookmarked: false,
        languages: [
            'react',
            'state management'
        ],
        isNPM: false,
    },
    {
        id: 16,
        logo: 'https://i.ibb.co.com/09HR03H/images-2.png',
        name: 'vuex',
        description: 'Vuex is a state management library for Vue.js applications that centralizes the application state. It allows components to share data easily and manages state changes predictably, improving maintainability and debugging.',
        websiteUrl: 'https://vuex.vuejs.org/',
        isBookmarked: false,
        languages: [
            'vue',
            'state management'
        ],
        isNPM: false,
    },
    {
        id: 17,
        logo: 'https://i.ibb.co.com/PDd8Y3k/82210087.png',
        name: 'pinia',
        description: 'Pinia is a state management library for Vue.js that offers a simple API and centralized state management. It supports TypeScript and integrates seamlessly with Vue\'s reactivity system for modern applications.',
        websiteUrl: 'https://pinia.vuejs.org/',
        isBookmarked: false,
        languages: [
            'vue',
            'state management'
        ],
        isNPM: false,
    },
    {
        id: 18,
        logo: 'https://i.ibb.co.com/CWSNksV/images-3.png',
        name: 'react router',
        description: 'React Router is a library for managing navigation in React applications. It allows developers to define routes, handle URL changes, and render components based on the current path, enhancing user experience.',
        websiteUrl: 'https://reactrouter.com/',
        isBookmarked: false,
        languages: [
            'react',
            'routing'
        ],
        isNPM: false,
    },
    {
        id: 19,
        logo: 'https://i.ibb.co.com/98ZNKm3/97daead1c859abcbc76e8ff6eb39d482.jpg',
        name: 'vue router',
        description: 'Vue Router is the official routing library for Vue.js that enables navigation between components. It helps create single-page applications with dynamic URL handling for a seamless user experience.',
        websiteUrl: 'https://router.vuejs.org/',
        isBookmarked: false,
        languages: [
            'vue',
            'routing'
        ],
        isNPM: false,
    },
    {
        id: 20,
        logo: 'https://i.ibb.co.com/CBgh683/images-5.png',
        name: 'tailwind css',
        description: 'Tailwind CSS is a utility-first CSS framework that allows developers to create custom designs quickly using predefined classes, promoting responsiveness and reducing the need for custom CSS.',
        websiteUrl: 'https://tailwindcss.com/',
        isBookmarked: false,
        languages: [
            'css'
        ],
        isNPM: false,
    },
    {
        id: 21,
        logo: 'https://i.ibb.co.com/tQ9ckJ3/images-6.png',
        name: 'bulma',
        description: 'Bulma is a modern CSS framework based on Flexbox that offers a responsive and mobile-first design. It provides a variety of pre-built components and a simple syntax, making it easy for developers to create stylish and user-friendly web interfaces.',
        websiteUrl: 'https://bulma.io/',
        isBookmarked: false,
        languages: [
            'css'
        ],
        isNPM: false,
    },
    {
        id: 22,
        logo: 'https://i.ibb.co.com/BqnQzhz/emotion.png',
        name: 'emotion (css in js)',
        description: 'Emotion is a popular CSS-in-JS library for styling React applications. It allows developers to write CSS styles directly within JavaScript, providing powerful features like dynamic styling, theming, and scoped styles while maintaining excellent performance and a developer-friendly experience.',
        websiteUrl: 'https://emotion.sh/docs/introduction',
        isBookmarked: false,
        languages: [
            'css',
            'javascript'
        ],
        isNPM: false,
    },
    {
        id: 23,
        logo: 'https://i.ibb.co.com/R7CKyJ7/images-7.png',
        name: 'sass',
        description: 'Sass (Syntactically Awesome Style Sheets) is a CSS preprocessor that extends CSS with features like variables, nesting, and mixins, making stylesheets more efficient and organized for easier management.',
        websiteUrl: 'https://sass-lang.com/',
        isBookmarked: false,
        languages: [
            'css',
        ],
        isNPM: false,
    },
    {
        id: 24,
        logo: 'https://i.ibb.co.com/QX2cp6G/images-9.png',
        name: 'postcss',
        description: 'PostCSS is a tool for transforming CSS with JavaScript plugins. It allows developers to use features like autoprefixing, CSS variables, and nesting, helping to optimize and enhance the styling process while ensuring compatibility across different browsers.',
        websiteUrl: 'https://postcss.org/',
        isBookmarked: false,
        languages: [
            'css',
        ],
        isNPM: false,
    },
    {
        id: 25,
        logo: 'https://i.ibb.co.com/1vV2zyJ/formik-icon-1024x1024-deyd4zqw.png',
        name: 'formik',
        description: 'Formik is a popular library for managing forms in React applications. It simplifies form handling by providing features like validation, error handling, and form state management, allowing developers to build complex forms with ease and efficiency.',
        websiteUrl: 'https://formik.org/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 26,
        logo: 'https://i.ibb.co.com/4KrQpxC/react-hook-form-logo-only.png',
        name: 'react hook form',
        description: 'React Hook Form is a library for managing form state in React applications. It leverages React hooks to provide a simple and efficient way to handle form validation, error messages, and submission, minimizing the amount of code needed and enhancing performance.',
        websiteUrl: 'https://react-hook-form.com/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 27,
        logo: 'https://i.ibb.co.com/q1rvD8Q/logo-1.png',
        name: 'vee validate',
        description: 'Vee Validate is a validation library for Vue.js that simplifies form validation. It provides a set of rules and a flexible API to handle validations easily, allowing developers to ensure user inputs are correct and display error messages effectively in their Vue applications.',
        websiteUrl: 'https://vee-validate.logaretm.com/v4/',
        isBookmarked: false,
        languages: [
            'vue',
        ],
        isNPM: true,
    },
    {
        id: 28,
        logo: 'https://i.ibb.co.com/KzWPp2m/jest-js7858-logowik-com.webp',
        name: 'jest (testing library)',
        description: 'Jest is a JavaScript testing framework developed by Facebook, widely used for testing React applications. It provides a simple and intuitive API, supports snapshot testing, and includes features like mocking and code coverage, making it easy to write and run tests efficiently.',
        websiteUrl: 'https://jestjs.io/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 29,
        logo: 'https://i.ibb.co.com/PMj623Z/react-testing-libraries-and-tools-of-2022-5-a67f5cc303.png',
        name: 'Mocha (testing library)',
        description: 'Mocha.js is a JavaScript testing framework for Node.js and browser applications. It offers a flexible structure for organizing tests, supports asynchronous testing, and can be paired with various assertion libraries, making it easy to create and run tests effectively.',
        websiteUrl: 'https://mochajs.org/',
        isBookmarked: false,
        languages: [
            'react',
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 30,
        logo: 'https://i.ibb.co.com/yYgfxjB/images.jpg',
        name: 'cypress (end to end testing library)',
        description: 'Cypress is an end-to-end testing framework for web applications that enables developers to write and debug tests directly in the browser. It offers real-time reloads and a user-friendly interface for monitoring test execution.',
        websiteUrl: 'https://www.cypress.io/',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 31,
        logo: 'https://i.ibb.co.com/SQx8yLM/images-10.png',
        name: 'Puppeteer',
        description: 'Puppeteer is a Node.js library that allows developers to control headless Chrome or Chromium browsers through a high-level API. It’s commonly used for automating web tasks, including web scraping, testing, and generating screenshots or PDFs of web pages.',
        websiteUrl: 'https://pptr.dev/',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 32,
        logo: 'https://i.ibb.co.com/kBP06f2/images-11.png',
        name: 'framer motion',
        description: 'Framer Motion is a React animation library that offers a simple API for creating smooth animations and transitions. It supports gestures and layout animations, enhancing user experiences in web applications.',
        websiteUrl: 'https://www.framer.com/motion/',
        isBookmarked: false,
        languages: [
            'react',
            'animation library'
        ],
        isNPM: true,
    },
    {
        id: 33,
        logo: 'https://i.ibb.co.com/GFDhx0c/h28j-J1q-M-400x400.jpg',
        name: 'gsap',
        description: 'GSAP (GreenSock Animation Platform) is a powerful JavaScript library for high-performance animations. It offers a simple API to animate CSS properties, SVG, and JavaScript objects, making complex animations easy to implement.',
        websiteUrl: 'https://gsap.com/',
        isBookmarked: false,
        languages: [
            'react',
            'animation library'
        ],
        isNPM: true,
    },
    {
        id: 34,
        logo: 'https://i.ibb.co.com/yN9R3Lg/animejs.jpg',
        name: 'anime js',
        description: 'Anime.js is a lightweight JavaScript animation library that simplifies creating complex animations. It supports CSS, SVG, and JavaScript properties, providing an easy API for controlling timing and easing functions.',
        websiteUrl: 'https://animejs.com/',
        isBookmarked: false,
        languages: [
            'javascript',
            'animation library'
        ],
        isNPM: true,
    },
    {
        id: 35,
        logo: 'https://i.ibb.co.com/TcyW9c2/images-12.png',
        name: 'three js',
        description: 'Three.js is a JavaScript library for creating 3D graphics in the browser using WebGL. It offers an easy-to-use API for building interactive 3D scenes with lights, shadows, and animations.',
        websiteUrl: 'https://threejs.org/',
        isBookmarked: false,
        languages: [
            'javascript',
            'animation library'
        ],
        isNPM: true,
    },
    {
        id: 36,
        logo: 'https://i.ibb.co.com/c6Zw068/react-query9872-logowik-com.webp',
        name: 'React Query',
        description: 'React Query is a data-fetching library for React that simplifies managing server state. It offers caching, background updates, and synchronization, improving data handling and user experience in applications.',
        websiteUrl: 'https://tanstack.com/query/latest',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 37,
        logo: 'https://i.ibb.co.com/qJmFf1V/social-2.png',
        name: 'SWR (react hook)',
        description: 'SWR is a React hook library for data fetching, developed by Vercel. It stands for "stale-while-revalidate" and provides a simple way to handle caching, revalidation, and synchronization of data, ensuring fast and efficient data updates in React applications.',
        websiteUrl: 'https://swr.vercel.app/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 38,
        logo: 'https://i.ibb.co.com/bRcPR4Q/images.png',
        name: 'Lodash',
        description: 'Lodash is a JavaScript utility library offering helpful functions for tasks like working with arrays, objects, and strings, simplifying code and improving efficiency.',
        websiteUrl: 'https://lodash.com/',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 39,
        logo: 'https://i.ibb.co.com/kVLCDgh/25441705.png',
        name: 'Day JS',
        description: 'Day.js is a lightweight JavaScript library for working with dates and times. It provides a simple API for parsing, validating, manipulating, and formatting dates, similar to Moment.js, but with a much smaller footprint.',
        websiteUrl: 'https://day.js.org/',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 40,
        logo: 'https://i.ibb.co.com/SRVffCq/uuid-backfill.png',
        name: 'UUID',
        description: 'UUID (Universally Unique Identifier) is a 128-bit unique identifier used in databases and applications to ensure globally unique keys without requiring a central authority.',
        websiteUrl: 'https://www.npmjs.com/package/uuid',
        isBookmarked: false,
        languages: [
            'javascript',
            'react',
            'nextjs',
            'vue'
        ],
        isNPM: true,
    },
    {
        id: 41,
        logo: 'https://i.ibb.co.com/YNBgQ26/opengraph-image.png',
        name: 'Classnames',
        description: 'Classnames is a JavaScript utility for conditionally joining CSS class names, simplifying dynamic class application in React and other JavaScript applications.',
        websiteUrl: 'https://www.npmjs.com/package/classnames',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 42,
        logo: 'https://i.ibb.co.com/C0VhdxF/animatecss-opengraph.jpg',
        name: 'Classnames',
        description: 'Animate.css is a library of pre-built CSS animations that lets developers easily add engaging animations to web projects using simple class names.',
        websiteUrl: 'https://animate.style/',
        isBookmarked: false,
        languages: [
            'css',
            'animation library'
        ],
        isNPM: false,
    },
    {
        id: 43,
        logo: 'https://i.ibb.co.com/bL9yBcr/images-1.png',
        name: 'Nuxt js',
        description: 'Nuxt.js is a framework for building Vue.js applications that simplifies server-side rendering (SSR) and static site generation. It offers features like routing and automatic code splitting, enhancing performance and SEO.',
        websiteUrl: 'https://nuxt.com/',
        isBookmarked: false,
        languages: [
            'vue',
        ],
        isNPM: true,
    },
    {
        id: 44,
        logo: 'https://i.ibb.co.com/PYFknDZ/images-2.png',
        name: 'gatsby js',
        description: 'Gatsby is a React-based framework for building fast static websites. It uses GraphQL for data sourcing and optimizes performance with features like code splitting and image optimization, ideal for modern web development.',
        websiteUrl: 'https://www.gatsbyjs.com/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 45,
        logo: 'https://i.ibb.co.com/Dft24TS/logo-vertical.png',
        name: 'Firebase',
        description: 'Firebase is a Google platform offering tools for building web and mobile applications, including real-time databases, authentication, cloud storage, and hosting, enabling quick and scalable app development.',
        websiteUrl: 'https://firebase.google.com/',
        isBookmarked: false,
        languages: [
            'react',
            'nextjs',
            'javascript',
            'vue'
        ],
        isNPM: true,
    },
    {
        id: 46,
        logo: 'https://i.ibb.co.com/p294HZv/images-3.png',
        name: 'Auth0',
        description: 'Auth0 is an authentication platform that simplifies securing apps with features like social login, single sign-on (SSO), and multi-factor authentication (MFA), making identity management easy for developers.',
        websiteUrl: 'https://auth0.com/',
        isBookmarked: false,
        languages: [
            'react'
        ],
        isNPM: true,
    },
    {
        id: 47,
        logo: 'https://i.ibb.co.com/Qp9ndYw/og.jpg',
        name: 'TS-Node',
        description: 'TS-Node is an execution environment for running TypeScript directly in Node.js without precompilation, combining TypeScript\'s type-checking with Node.js runtime for easier development.',
        websiteUrl: 'https://www.npmjs.com/package/ts-node',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 48,
        logo: 'https://i.ibb.co.com/g76cg7Q/images.jpg',
        name: 'dropzone',
        description: 'Dropzone.js is a JavaScript library that simplifies drag-and-drop file uploads, offering features like file previews, progress bars, and multiple file uploads for a smoother user experience.',
        websiteUrl: 'https://www.dropzone.dev/',
        isBookmarked: false,
        languages: [
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 49,
        logo: 'https://i.ibb.co.com/26VH4mP/images-1.jpg',
        name: 'zustand',
        description: 'Zustand is a lightweight state management library for React. It offers a simple API, minimal re-renders, and easy state updates, making it great for managing state in React apps with minimal complexity.',
        websiteUrl: 'https://zustand-demo.pmnd.rs/',
        isBookmarked: false,
        languages: [
            'react',
            'nextjs',
            'state management'
        ],
        isNPM: true,
    },
    {
        id: 50,
        logo: 'https://i.ibb.co.com/QMp8S8j/jotai-mascot.png',
        name: 'jotai',
        description: 'Jotai is a flexible state management library for React that uses atomic state units for fine-grained reactivity. Its simple API allows for easy state sharing across components in applications.',
        websiteUrl: 'https://jotai.org/',
        isBookmarked: false,
        languages: [
            'react',
            'state management'
        ],
        isNPM: true,
    },
    {
        id: 51,
        logo: 'https://i.ibb.co.com/wsZ3pb6/e971f56e23d8bab19e47b898c4a589a4.png',
        name: 'recoil js',
        description: 'Recoil is a state management library for React that offers a simple way to manage global state with fine-grained updates. It allows components to subscribe to specific state pieces, enhancing React\'s state management.',
        websiteUrl: 'https://recoiljs.org/',
        isBookmarked: false,
        languages: [
            'react',
            'state management'
        ],
        isNPM: true,
    },
    {
        id: 52,
        logo: 'https://i.ibb.co.com/VSbhnGv/styled-components.png',
        name: 'styled components',
        description: 'Styled components is a library for styling React apps using tagged template literals. It allows CSS to be written directly in JavaScript, enabling dynamic styles based on props and ensuring styles are component-scoped.',
        websiteUrl: 'https://styled-components.com/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 53,
        logo: 'https://i.ibb.co.com/DGfYGTt/images-2.jpg',
        name: 'Next Auth',
        description: 'NextAuth.js is an authentication library for Next.js that simplifies adding authentication. It supports various providers, offering a flexible and secure way to manage user sessions and protect routes.',
        websiteUrl: 'https://authjs.dev/',
        isBookmarked: false,
        languages: [
            'nextjs',
        ],
        isNPM: true,
    },
    {
        id: 54,
        logo: 'https://i.ibb.co.com/Gt5BBxC/14921202.png',
        name: 'date fns',
        description: 'Date fns is a lightweight JavaScript library for date manipulation and formatting. It provides various functions for parsing and validating dates, making date operations easier while keeping the bundle size small.',
        websiteUrl: 'https://date-fns.org/',
        isBookmarked: false,
        languages: [
            'nextjs',
            'react',
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 55,
        logo: 'https://i.ibb.co.com/2jcBkLg/images.png',
        name: 'free code camp',
        description: 'freeCodeCamp is a free, interactive learning platform that teaches coding and web development. It offers a wide range of tutorials, coding challenges, and projects, allowing users to learn programming languages and frameworks at their own pace.',
        websiteUrl: 'https://www.freecodecamp.org/',
        isBookmarked: false,
        languages: [
            'nextjs',
            'react',
            'vue',
            'learning platform',
            'javascript'
        ],
        isNPM: false,
    },
    {
        id: 56,
        logo: 'https://i.ibb.co.com/TRSdDnq/images-1.png',
        name: 'codecademy',
        description: 'Codecademy is an online platform offering interactive coding courses. It covers topics like web development and data science, helping users learn through hands-on exercises and projects.',
        websiteUrl: 'https://www.codecademy.com/',
        isBookmarked: false,
        languages: [
            'react',
            'learning platform',
            'javascript'
        ],
        isNPM: false,
    },
    {
        id: 57,
        logo: 'https://i.ibb.co.com/rsvP4X6/Coursera-Logo-600x600-svg.png',
        name: 'coursera',
        description: 'Coursera is an online learning platform that offers courses, specializations, and degrees from universities and institutions. It covers a wide range of subjects, including technology, business, and science, allowing users to learn at their own pace.',
        websiteUrl: 'https://www.coursera.org/',
        isBookmarked: false,
        languages: [
            'learning platform',
        ],
        isNPM: false,
    },
    {
        id: 58,
        logo: 'https://i.ibb.co.com/QJNkXtv/edx-logo-icon-248968.webp',
        name: 'edx',
        description: 'edX is an online platform offering courses from top universities on subjects like technology, business, and science. Users can learn at their own pace or earn verified certificates.',
        websiteUrl: 'https://www.edx.org/',
        isBookmarked: false,
        languages: [
            'learning platform',
        ],
        isNPM: false,
    },
    {
        id: 59,
        logo: 'https://i.ibb.co.com/3MjjHkz/images-2.png',
        name: 'leetcode',
        description: 'LeetCode is an online platform offering coding challenges and problems to help developers improve their programming skills. It covers topics like algorithms and data structures, and is popular for preparing for technical interviews.',
        websiteUrl: 'https://leetcode.com/',
        isBookmarked: false,
        languages: [
            'problem solving platform',
        ],
        isNPM: false,
    },
    {
        id: 60,
        logo: 'https://i.ibb.co.com/B2q4S2W/Hacker-Rank-logo.png',
        name: 'hackerrank',
        description: 'HackerRank is an online platform offering coding challenges and competitions to help developers improve skills and prepare for technical interviews. It covers various languages and domains like algorithms and data structures.',
        websiteUrl: 'https://www.hackerrank.com/',
        isBookmarked: false,
        languages: [
            'problem solving platform',
        ],
        isNPM: false,
    },
    {
        id: 61,
        logo: 'https://i.ibb.co.com/YDBr6Qk/images-3.png',
        name: 'codewars',
        description: 'Codewars is an online platform offering coding challenges, called "kata," for developers to improve their skills. Users can solve problems in multiple languages and collaborate with the community.',
        websiteUrl: 'https://www.codewars.com/',
        isBookmarked: false,
        languages: [
            'problem solving platform',
        ],
        isNPM: false,
    },
    {
        id: 62,
        logo: 'https://i.ibb.co.com/54F4VRr/5624255.png',
        name: 'exercism',
        description: 'Exercism is an online platform that provides coding exercises to help developers improve their programming skills. It offers practice in various languages and features mentorship and community support, enabling users to receive feedback on their solutions.',
        websiteUrl: 'https://exercism.org/',
        isBookmarked: false,
        languages: [
            'coding practice platform',
        ],
        isNPM: false,
    },
    {
        id: 63,
        logo: 'https://i.ibb.co.com/V9b6tMh/9b6ced80-dedc-11ea-8248-71ff8952791c.png',
        name: 'VisuAlgo',
        description: 'VisuAlgo is an online visualizer that helps users understand algorithms and data structures through interactive animations. It covers topics like sorting and graph algorithms, simplifying complex concepts.',
        websiteUrl: 'https://visualgo.net/en',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 64,
        logo: 'https://i.ibb.co.com/B6bsr7L/channels4-profile.jpg',
        name: 'MIT OpenCourseWare',
        description: 'MIT OpenCourseWare (OCW) is an online platform that provides free access to course materials from a wide range of MIT\'s academic programs. It offers lecture notes, videos, assignments, and exams, enabling learners worldwide to study various subjects at their own pace.',
        websiteUrl: 'https://www.youtube.com/@mitocw/search?query=data%20structure',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 65,
        logo: 'https://i.ibb.co.com/qmzg3kc/unnamed.jpg',
        name: 'my code school',
        description: 'mycodeschool was a YouTube channel offering clear, educational videos on programming, data structures, and algorithms, helping beginners and intermediates understand complex topics easily.',
        websiteUrl: 'https://www.youtube.com/@mycodeschool/search?query=dsa',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 66,
        logo: 'https://i.ibb.co.com/gP7KZmN/unnamed-1.jpg',
        name: 'Back To Back SWE',
        description: 'Back To Back SWE is a YouTube channel that focuses on technical interview preparation, covering topics like algorithms, data structures, and system design. It provides detailed explanations and problem-solving strategies to help developers succeed in coding interviews.',
        websiteUrl: 'https://www.youtube.com/@BackToBackSWE/search?query=dsa',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 67,
        logo: 'https://i.ibb.co.com/YcSvQhS/20487725.png',
        name: 'The Algorithms',
        description: 'TheAlgorithms is a GitHub repository offering open-source implementations of algorithms in various programming languages. It serves as a resource for learning and practicing algorithms, covering a wide range of topics like sorting, searching, and graph algorithms.',
        websiteUrl: 'https://github.com/TheAlgorithms',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 68,
        logo: 'https://i.ibb.co.com/Dzcxyk6/16903644.jpg',
        name: 'interviews',
        description: 'Interviews, especially technical ones, assess problem-solving skills and knowledge of algorithms, data structures, and system design. Preparation often includes coding challenges and mock interviews.',
        websiteUrl: 'https://github.com/kdn251/interviews',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 69,
        logo: 'https://i.ibb.co.com/0ZYBTjk/https-www-bigocheatsheet-com-img-big-o-cheat-sheet-poster.png',
        name: 'big o cheatsheet',
        description: 'Big-O Cheat Sheet provides time and space complexities for common data structures and algorithms. It\'s a quick reference for understanding operation efficiency, useful for code optimization and interview prep.',
        websiteUrl: 'https://www.bigocheatsheet.com/',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 70,
        logo: 'https://i.ibb.co.com/fD9spFP/unnamed-2.jpg',
        name: 'CS Dojo',
        description: 'CS Dojo is a YouTube channel that offers tutorials on coding, algorithms, and interview preparation. It provides clear explanations of complex topics, helping beginners and intermediate learners improve their programming skills and prepare for technical interviews.',
        websiteUrl: 'https://www.youtube.com/@CSDojo/search?query=dsa',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 71,
        logo: 'https://i.ibb.co.com/dgfcR3W/unnamed-3.jpg',
        name: 'Abdul Bari',
        description: 'Abdul Bari is a YouTube educator known for clear tutorials on data structures and algorithms. His videos simplify complex topics, making them accessible for learners and those preparing for technical interviews.',
        websiteUrl: 'https://www.youtube.com/@abdul_bari/search?query=dsa',
        isBookmarked: false,
        languages: [
            'dsa',
        ],
        isNPM: false,
    },
    {
        id: 72,
        logo: 'https://i.ibb.co.com/TWBBfPD/images-5.png',
        name: 'at coder',
        description: 'AtCoder is a competitive programming platform that hosts contests and provides a variety of coding challenges. It offers problems across different difficulty levels, allowing programmers to practice and improve their skills while competing with others globally.',
        websiteUrl: 'https://atcoder.jp/',
        isBookmarked: false,
        languages: [
            'problem solving platform',
        ],
        isNPM: false,
    },
    {
        id: 73,
        logo: 'https://i.ibb.co.com/ccgnrbh/images.jpg',
        name: 'codeforces',
        description: 'Codeforces is a competitive programming platform that hosts regular contests and offers a wide range of coding problems. It allows programmers to practice, improve their skills, and compete against others in a global community, with features like problem ratings and user rankings.',
        websiteUrl: 'https://codeforces.com/',
        isBookmarked: false,
        languages: [
            'problem solving platform',
        ],
        isNPM: false,
    },
    {
        id: 74,
        logo: 'https://i.ibb.co.com/Ry6wHcj/1599134270336.jpg',
        name: 'code chef',
        description: 'CodeChef is a competitive programming platform that hosts contests and offers a wide range of problems. It helps users improve their coding skills and learn from a community of programmers.',
        websiteUrl: 'https://www.codechef.com/',
        isBookmarked: false,
        languages: [
            'problem solving platform',
        ],
        isNPM: false,
    },
    {
        id: 75,
        logo: 'https://i.ibb.co.com/yRd60H9/unnamed.png',
        name: 'geeks for geeks',
        description: 'GeeksforGeeks is an online platform that offers a wealth of resources for computer science and programming topics. It features articles, tutorials, coding challenges, and interview preparation materials, making it a valuable resource for students and professionals alike.',
        websiteUrl: 'https://www.geeksforgeeks.org/',
        isBookmarked: false,
        languages: [
            'learning platform',
        ],
        isNPM: false,
    },
    {
        id: 76,
        logo: 'https://i.ibb.co.com/cCqQ9ym/unnamed-4.jpg',
        name: 'codin game',
        description: 'Codin Game is an online platform that offers a fun and interactive way to improve coding skills through games and challenges. It provides various programming puzzles across multiple languages, allowing users to learn and compete while enhancing their problem-solving abilities.',
        websiteUrl: 'https://www.codingame.com/start/',
        isBookmarked: false,
        languages: [
            'coding practice platform',
        ],
        isNPM: false,
    },
    {
        id: 77,
        logo: 'https://i.ibb.co.com/vzrbhDQ/images-1.jpg',
        name: 'react lazyload',
        description: 'react-lazyload is a React component that helps optimize the loading of images and other components by delaying their rendering until they are in the viewport. This improves page performance and reduces initial loading time, enhancing user experience, especially on image-heavy websites.',
        websiteUrl: 'https://www.npmjs.com/package/react-lazyload',
        isBookmarked: false,
        languages: [
            'react',
            'nextjs'
        ],
        isNPM: true,
    },
    {
        id: 78,
        logo: 'https://i.ibb.co.com/SsvnbfH/infinite-scroll-in-react-apps.webp',
        name: 'react infinite scroll component',
        description: 'The React Infinite Scroll Component loads and displays data in a scrolling list without pagination. New data is fetched and appended as users scroll, enhancing the browsing experience seamlessly.',
        websiteUrl: 'https://www.npmjs.com/package/react-infinite-scroll-component',
        isBookmarked: false,
        languages: [
            'react',
            'nextjs'
        ],
        isNPM: true,
    },
    {
        id: 79,
        logo: 'https://i.ibb.co.com/H4BtM3Y/nextjs-image1.webp',
        name: 'next image',
        description: 'next image is an image optimization component in Next.js that automatically optimizes images on demand. It supports lazy loading, resizing, and serving images in modern formats like WebP, enhancing performance and improving user experience in web applications.',
        websiteUrl: 'https://nextjs.org/docs/pages/api-reference/components/image',
        isBookmarked: false,
        languages: [
            'nextjs'
        ],
        isNPM: true,
    },
    {
        id: 80,
        logo: 'https://i.ibb.co.com/zx7Pq1y/eyecatch-recharts-1200x630.webp',
        name: 'recharts',
        description: 'Recharts is a composable charting library for React, built on D3.js. It provides a set of customizable components for creating responsive and interactive charts like line, bar, and pie charts. Recharts simplifies the process of data visualization, making it easy to integrate and use in React applications.',
        websiteUrl: 'https://recharts.org/en-US/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 81,
        logo: 'https://i.ibb.co.com/0QWLT48/Chart-js-logo-svg.png',
        name: 'chart js',
        description: 'Chart.js is a popular open-source JavaScript library for creating interactive and responsive charts. It supports various chart types, including bar, line, pie, and radar charts, using HTML5 canvas.',
        websiteUrl: 'https://www.chartjs.org/',
        isBookmarked: false,
        languages: [
            'react',
            'javascript'
        ],
        isNPM: true,
    },
    {
        id: 82,
        logo: 'https://avatars.githubusercontent.com/u/39895671?s=48&v=4',
        name: 'react icons',
        description: 'React Icons is a library offering popular icon sets as React components, enabling easy and customizable icon integration in applications, enhancing UI design and development efficiency.',
        websiteUrl: 'https://react-icons.github.io/react-icons/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 83,
        logo: 'https://avatars.githubusercontent.com/u/8546082?s=200&v=4',
        name: 'internationalization',
        description: 'i18next is a powerful internationalization framework for JavaScript. The React i18next library integrates it with React, simplifying multi-language support and translation management in applications.',
        websiteUrl: 'https://react.i18next.com/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 85,
        logo: 'https://miro.medium.com/v2/resize:fit:828/format:webp/1*eKrABZ5AHVzUiU07hsMKjw.jpeg',
        name: 'dot env',
        description: 'Dotenv is a lightweight module that loads environment variables from a .env file into process.env. It\'s commonly used to manage configuration settings like API keys and database credentials, making it easier to maintain secure and environment-specific configurations in Node.js applications.',
        websiteUrl: 'https://www.npmjs.com/package/dotenv',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 86,
        logo: 'https://img.freepik.com/premium-vector/local-storage-logo-design-vector-illustration_685330-1197.jpg?w=900',
        name: 'use local storage state',
        description: 'use-local-storage-state is a React hook that simplifies working with localStorage. It allows you to store, retrieve, and update state directly in localStorage, ensuring data persistence across browser sessions while keeping state management intuitive and efficient.',
        websiteUrl: 'https://www.npmjs.com/package/use-local-storage-state',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 87,
        logo: 'https://repository-images.githubusercontent.com/327040825/a859e780-da82-11eb-9614-0109d8fc9bab',
        name: 'next seo',
        description: 'next seo is a Next.js plugin that simplifies adding meta tags, Open Graph, and structured data, helping improve SEO and enhancing the visibility of your Next.js applications.',
        websiteUrl: 'https://www.npmjs.com/package/next-seo',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 88,
        logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg58mObmoRL8n_bOZ8zLVhmlINdjsAgIa-Hw&s',
        name: 'vueuse',
        description: 'VueUse is a collection of utility functions for Vue.js, offering composable functions to simplify tasks like state management and event handling, enhancing efficiency in Vue 3 development.',
        websiteUrl: 'https://www.npmjs.com/package/@vueuse/core',
        isBookmarked: false,
        languages: [
            'vue',
        ],
        isNPM: true,
    },
    {
        id: 89,
        logo: 'https://i.ibb.co.com/L9gz9kv/png-transparent-lottiefiles-app-logo-tech-companies-thumbnail.png',
        name: 'lottie files',
        description: 'LottieFiles is a platform for integrating lightweight, scalable Lottie animations into apps and websites, enhancing visual appeal and improving user experience with minimal file sizes.',
        websiteUrl: 'https://lottiefiles.com/',
        isBookmarked: false,
        languages: [
            'animation library',
        ],
        isNPM: false,
    },
    {
        id: 90,
        logo: 'https://i.ibb.co.com/h2Q8nDg/demo-fb-preview.jpg',
        name: 'scroll magic',
        description: 'Scroll Magic is a JavaScript library for creating scroll-driven animations. It allows developers to trigger animations based on scroll position, enhancing user engagement and storytelling on websites.',
        websiteUrl: 'https://scrollmagic.io/',
        isBookmarked: false,
        languages: [
            'animation library',
            'javascript',
        ],
        isNPM: true,
    },
    {
        id: 91,
        logo: 'https://i.ibb.co.com/48LRVNv/9039853.png',
        name: 'mo.js',
        description: 'Mo.js is a powerful motion graphics library for JavaScript that simplifies creating complex animations and effects. It offers a modular approach, allowing developers to build custom animations easily, and is optimized for performance, making it suitable for web and mobile applications.',
        websiteUrl: 'https://mojs.github.io/',
        isBookmarked: false,
        languages: [
            'animation library',
            'javascript',
        ],
        isNPM: true,
    },
    {
        id: 92,
        logo: 'https://i.ibb.co.com/prJXGf2/14272617.png',
        name: 'pop motion',
        description: 'Pop motion is a versatile JavaScript animation library for creating fluid, interactive animations and gestures. It supports physics-based and keyframe animations, enhancing user experience with smooth effects.',
        websiteUrl: 'https://popmotion.io/',
        isBookmarked: false,
        languages: [
            'animation library',
            'javascript',
        ],
        isNPM: true,
    },
    {
        id: 93,
        logo: 'https://i.ibb.co.com/xD7NLnw/8120cf7038891131ed5e375cbb4b948e.png',
        name: 'zzz',
        description: 'Zdog is a 3D JavaScript engine for creating simple and playful animations. It offers an easy-to-use API for building 3D shapes and animations in the browser, making it ideal for creating interactive and engaging designs with minimal effort.',
        websiteUrl: 'https://zzz.dog/',
        isBookmarked: false,
        languages: [
            'animation library',
            'javascript',
        ],
        isNPM: false,
    },
    {
        id: 94,
        logo: 'https://pbs.twimg.com/profile_images/703421064391454722/CT9ZCnCA_400x400.jpg',
        name: 'dixonand moe',
        description: 'A lightweight vanilla JavaScript parallax library that provides smooth parallax scrolling animations. It offers a simple API for building complex transitions, focusing on performance and user experience.',
        websiteUrl: 'https://dixonandmoe.com/rellax/',
        isBookmarked: false,
        languages: [
            'animation library',
            'javascript',
        ],
        isNPM: false,
    },
    {
        id: 95,
        logo: 'https://i.ibb.co.com/Z27Nx53/images-8.png',
        name: 'barba js',
        description: 'Barba.js is a JavaScript library for creating smooth page transitions in web applications. It enables developers to manage and animate the transitions between different pages, enhancing user experience by providing seamless navigation without full page reloads.',
        websiteUrl: 'https://barba.js.org/',
        isBookmarked: false,
        languages: [
            'animation library',
            'javascript',
        ],
        isNPM: true,
    },
    {
        id: 96,
        logo: 'https://i.ibb.co.com/dMqDzg9/images.png',
        name: 'MobX',
        description: 'MobX is a reactive state management library for JavaScript, simplifying state updates and making UI changes automatic and efficient in dynamic applications.',
        websiteUrl: 'https://mobx.js.org/README.html',
        isBookmarked: false,
        languages: [
            'nextjs',
            'state management',
        ],
        isNPM: true,
    },
    {
        id: 97,
        logo: 'https://i.ibb.co.com/BrKqYSx/16309564.png',
        name: 'react markdown',
        description: 'Remark.js is a JavaScript library that transforms Markdown content into interactive slide presentations, enabling quick formatting and customization for clean, responsive presentations.',
        websiteUrl: 'https://remarkjs.github.io/react-markdown/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 98,
        logo: 'https://i.ibb.co.com/hySSXVC/37453691.png',
        name: 'MDX js',
        description: 'MDX is a JSX-based format that combines Markdown with embedded React components, allowing developers to create rich, interactive content and documentation easily for modern web applications.',
        websiteUrl: 'https://mdxjs.com/',
        isBookmarked: false,
        languages: [
            'react',
        ],
        isNPM: true,
    },
    {
        id: 99,
        logo: 'https://i.ibb.co.com/Tbtnm4D/120650344.png',
        name: 'roadmap sh',
        description: 'Roadmap.sh is an interactive platform that provides visual learning paths for various tech stacks and roles, helping developers understand the skills and technologies needed for their career goals. It offers a structured approach to learning through clear roadmaps and resources.',
        websiteUrl: 'https://roadmap.sh/',
        isBookmarked: false,
        languages: [],
        isNPM: false,
    },
    {
        id: 100,
        logo: 'https://i.ibb.co.com/QF7xrX2/logo.png',
        name: 'ship fast',
        description: 'Ship fast is a tool for developers that simplifies the process of deploying and managing applications. It provides a streamlined platform for continuous deployment, enabling faster release cycles and easier updates, enhancing productivity and collaboration for development teams.',
        websiteUrl: 'https://shipfa.st/',
        isBookmarked: false,
        languages: [],
        isNPM: false,
    },
    {
        id: 101,
        logo: 'https://i.ibb.co.com/zrD8PPb/Zfsb-Oxnx-200x200.jpg',
        name: 'landing folio',
        description: 'Landing folio is a curated collection of landing page designs and templates, showcasing various styles and layouts for inspiration. It helps designers and developers find creative ideas for their own landing pages, enhancing user engagement and conversion rates.',
        websiteUrl: 'https://www.landingfolio.com/',
        isBookmarked: false,
        languages: [],
        isNPM: false,
    },
]